spring:
  profiles:
    active: dev

  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

    # excluded-view-names:
    # prefix: /templates/
    # suffix: .html

server:
  port: 8081

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

## Web Page Properties.
layout:
  sidebar:
    menuA_A: 메뉴명을 입력 (application.yml)

dbshowapi:
  url:
    sqlApplication: sqlApplicationList/{dbName}/{commandType}/{owner}/{tableName}
    sqlDetail: sqlDetail/{dbName}/{searchType}/{searchString}
    refObject: referencedObject/{dbName}/{objectType}/{owner}/{objectName}
    daSyncData: daSyncData/{tableName}

---
spring:
  profiles: local

  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5

#
#  datasource:
#    db1:
#      jdbcUrl: jdbc:mysql://localhost:3306/landcrawler?serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=UTF-8
#      driver-class-name: com.mysql.jdbc.Driver
#      username: landcrawler
#      password: landcrawler


---
spring:
  profiles: dev

  api:
    baseUrl: http://172.28.114.66:8082/api

  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5

---
spring:
  profiles: stage

  api:
    baseUrl: http://172.28.114.66:8082/api

  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
