spring:
  profiles:
    active: local

mybatis:
  mapper-locations: mybatis/mapper/**/*.xml

---
spring:
  profiles: local

  datasource:
    db1:
      jdbcUrl: jdbc:mysql://localhost:3306/landcrawler?serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=UTF-8
      driver-class-name: com.mysql.jdbc.Driver
      username: landcrawler
      password: landcrawler

    maindb:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbcUrl: jdbc:oracle:thin:@10.211.55.4:1526:NO03
      username: tmall
      password: tmall
      validation-query: select 1 from dual


---
spring:
  profiles: dev

  datasource:
    maindb:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbcUrl: jdbc:oracle:thin:@10.40.44.105:10101:TMALL
      username: tmall
      password: tmall#stg1
      validation-query: select 1 from dual

