spring:
  profiles:
    active: local

  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML

  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

    # excluded-view-names:
    # prefix: /templates/
    # suffix: .html


#tomcat:
#  ajp:
#    protocol: AJP/1.3
#    port: 18009
#    enabled: true


server:
  port: 8081

#jasypt:
#  encryptor:
#    bean: jasyptStringEncryptor

## Web Page Properties.
layout:
  sidebar:
    menuA_B: menu_BBBB
    menuA_A:
      - menuOrd: 1
        menuName: 주제영역별 Data
        url:
      - menuOrd: 1.1
        menuName: 주제영역별 Data
        url: daTabSubjAreaList
      - menuOrd: 1.3
        menuName: Table 목록
        url: daTableList
      - menuOrd: 1.2
        menuName: 'Data Sync'
        url: daSyncData
      - menuOrd: 1.4
        menuName: Table 상세
        url: tableDetail


dbshowapi:
  list:
    - url: sqlDetail/{dbName}/{searchType}/{searchString}
    - url: daSyncData/{tableName}
    - url: datables?tableName=&logicalAreaCd=&logicalAreaCd2=
    - url: logicalArea?logicAreaCd=

---
spring:
  profiles: local

  api:
    baseUrl: http://localhost:8082/api

  data:
    mongodb:
      uri: mongodb://172.28.114.66:27017,172.28.115.66:27017
      database: dbshow
      username: dbshow
      password: dbshow

---
spring:
  profiles: dev

  api:
    baseUrl: http://172.28.114.66:8082/api  #11DevDBb-da-dev01

  data:
    mongodb:
      uri: mongodb://172.28.114.66:27017,172.28.115.66:27017
      database: dbshow
      username: dbshow
      password: dbshow

---
spring:
  profiles: stage

  api:
    baseUrl: http://172.28.115.66:8082/api   #11DevDBb-da-dev02

  data:
    mongodb:
#      host: 172.28.114.66
#      port: 27017
      uri: mongodb://172.28.114.66:27017,172.28.115.66:27017
      database: dbshow
      username: dbshow
      password: dbshow

---
spring:
  profiles: product

  api:
    baseUrl: http://172.28.37.197:8082/api

  data:
    mongodb:
      uri: mongodb://172.28.114.66:27017,172.28.115.66:27017
      database: dbshow
      username: dbshow
      password: dbshow

