spring:
  profiles:
    active: dev

  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML

  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

    # excluded-view-names:
    # prefix: /templates/
    # suffix: .html

server:
  port: 8081

#jasypt:
#  encryptor:
#    bean: jasyptStringEncryptor

## Web Page Properties.
layout:
  sidebar:
    menuA_A: 메뉴명을 입력 (application.yml)

dbshowapi:
  url:
    sqlApplication: sqlApplicationList/{dbName}/{commandType}/{owner}/{tableName}
    sqlDetail: sqlDetail/{dbName}/{searchType}/{searchString}
    refObject: referencedObject/{dbName}/{objectType}/{owner}/{objectName}
    daSyncData: daSyncData/{tableName}
    daTables: datables?tableName=&logicalAreaCd=&logicalAreaCd2=
    logicalArea: logicalArea?logicAreaCd=

---
spring:
  profiles: local

  api:
    baseUrl: http://localhost:8082/api

---
spring:
  profiles: dev

  api:
    baseUrl: http://172.28.114.66:8082/api

---
spring:
  profiles: stage

  api:
    baseUrl: http://172.28.114.66:8082/api

---
spring:
  profiles: product

  api:
    baseUrl: http://172.28.113.125:8082/api

